// File generated by FlutterFire CLI.
// Replace this file with the output of `flutterfire configure`
// from your Firebase project: https://console.firebase.google.com
//
// ⚠️ IMPORTANT: This is a PLACEHOLDER file.
// Run `flutterfire configure` in your project root and replace
// this file with the generated one before running the app.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ⚠️ Replace the values below with your actual Firebase project config.

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv27ccqwBVP57JujM4XBVZa-f6RP7bQvQ',
    appId: '1:8490898537:web:666b1787dbaa83468e3ef8',
    messagingSenderId: '8490898537',
    projectId: 'note-app-ffa71',
    authDomain: 'note-app-ffa71.firebaseapp.com',
    storageBucket: 'note-app-ffa71.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACqtOuFp1vp0xS8bKtxHi1_22HjTaFLno',
    appId: '1:8490898537:android:38e2d546deb3a0478e3ef8',
    messagingSenderId: '8490898537',
    projectId: 'note-app-ffa71',
    storageBucket: 'note-app-ffa71.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSvcRCILUXf8YcvVWKTgwzpTxQH7FIUOg',
    appId: '1:8490898537:ios:37421bd54c46025e8e3ef8',
    messagingSenderId: '8490898537',
    projectId: 'note-app-ffa71',
    storageBucket: 'note-app-ffa71.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR-API-KEY',
    appId: 'YOUR-APP-ID',
    messagingSenderId: 'YOUR-SENDER-ID',
    projectId: 'YOUR-PROJECT-ID',
    storageBucket: 'YOUR-PROJECT-ID.appspot.com',
    iosClientId: 'YOUR-IOS-CLIENT-ID',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR-API-KEY',
    appId: 'YOUR-APP-ID',
    messagingSenderId: 'YOUR-SENDER-ID',
    projectId: 'YOUR-PROJECT-ID',
    authDomain: 'YOUR-PROJECT-ID.firebaseapp.com',
    storageBucket: 'YOUR-PROJECT-ID.appspot.com',
  );
}
